var ramalan = [
        "Kucingmu sedang merencanakan kudeta di rumah.",
        "Hari ini kamu akan menemukan kunci yang hilang di tempat yang sudah kamu periksa berkali-kali.",
        "Seseorang di sekitar kamu sedang menyiapkan kejutan, tapi lupa hadiahnya.",
        "Besok kamu akan terjebak dalam percakapan yang kamu sendiri tidak mengerti.",
        "Tinggal beberapa hari lagi kamu bisa menggantikan alarm dengan burung berkicau.",
        "Hari ini kamu akan makan makanan yang kamu pikir kamu tidak suka, dan ternyata kamu benar.",
        "Orang yang meneleponmu malam ini akan salah sambung, tapi kamu akan mengobrol selama satu jam.",
        "Besok kamu akan melihat anjing yang kelihatan lebih bahagia daripada kamu.",
        "Seseorang akan memberimu pujian yang kamu butuh waktu lama untuk memahaminya.",
        "Hari ini kamu akan melewati pintu yang lebih sempit dari yang kamu ingat.",
        "Seseorang akan menanyakan jalan padamu, dan kamu akan berpura-pura tahu.",
        "Kamu akan menghabiskan waktu lebih lama memilih makanan daripada memakannya.",
        "Hari ini kamu akan melihat seekor burung yang mirip sekali dengan temanmu.",
        "Orang di sebelahmu sedang berpikir untuk mengganti karier menjadi seleb TikTok.",
        "Besok kamu akan bertemu orang yang yakin kamu adalah teman lama, tapi kamu tidak ingat siapa dia.",
        "Buku yang kamu tinggalkan di rak akan tiba-tiba menjadi menarik lagi.",
        "Kamu akan mendapatkan pesan misterius yang ternyata cuma typo.",
        "Hari ini kamu akan melihat dua orang yang kembar, tapi mereka tidak saling kenal.",
        "Seseorang akan memuji sepatu kamu, tapi dia sendiri tidak pakai sepatu.",
        "Kamu akan bermimpi jadi superhero, tapi cuma bisa terbang setinggi satu meter.",
        "Hari ini kamu akan menemukan uang di saku jaket yang sudah lama kamu lupakan.",
        "Orang yang bersin di sebelahmu tadi malam sedang berusaha mencetak rekor dunia.",
        "Besok kamu akan bertemu dengan orang yang punya nama sama denganmu, tapi lebih keren.",
        "Kamu akan menemukan barang yang hilang tepat di saat kamu tidak butuh.",
        "Seseorang akan mencoba berbicara dalam bahasa yang kamu tidak paham, dan kamu akan pura-pura mengerti.",
        "Kamu akan tertawa saat mendengar suara aneh dari perutmu di waktu yang paling tidak tepat.",
        "Hari ini kamu akan menyadari bahwa pisang lebih menarik dari yang kamu kira.",
        "Orang di seberangmu sedang memikirkan bagaimana cara mengalahkanmu dalam permainan tebak-tebakan.",
        "Besok kamu akan lupa password yang baru saja kamu buat.",
        "Hari ini kamu akan memecahkan rekor pribadi dalam menunda pekerjaan.",
        "Seseorang akan mencoba mengerjai kamu, tapi malah terjebak sendiri.",
        "Kamu akan bertemu orang yang mengira kamu adalah seorang selebriti.",
        "Hari ini kamu akan berbicara dengan kaca dan merasa lebih pintar setelahnya.",
        "Besok kamu akan membuat keputusan besar... tentang apa yang mau dimakan untuk sarapan.",
        "Orang yang mengirim pesan tengah malam padamu sedang bermimpi tentangmu, tapi mimpinya aneh.",
        "Kamu akan menemukan remote TV, tapi di ruangan yang tidak ada TV-nya.",
        "Hari ini kamu akan menang kontes yang tidak pernah kamu ikuti.",
        "Besok kamu akan melihat iklan yang benar-benar bikin kamu penasaran, tapi kamu lupa produknya.",
        "Seseorang akan memberikanmu nasihat yang sangat bijak, tapi kamu akan lupa setelah lima menit.",
        "Hari ini kamu akan menangis karena melihat meme yang terlalu lucu.",
        "Orang di sebelahmu sedang memikirkan cara untuk tidak terlihat canggung.",
        "Besok kamu akan mencoba menonton serial baru, tapi malah ketiduran.",
        "Seseorang akan menanyakan pendapatmu tentang film yang kamu tidak pernah tonton.",
        "Hari ini kamu akan mendengar gosip, tapi terlalu tidak masuk akal untuk dipercaya.",
        "Orang yang menatapmu dari kejauhan hanya ingin tahu di mana kamu membeli jaketmu.",
        "Besok kamu akan membuka pintu yang tidak pernah kamu sadari ada di rumahmu.",
        "Seseorang akan menirukan cara tertawamu, dan kamu akan mulai meragukan diri sendiri.",
        "Hari ini kamu akan mendapati dirimu tertawa sendirian di tempat umum.",
        "Orang di belakangmu dalam antrean sedang menghitung berapa lama kamu akan selesai.",
        "Besok kamu akan lupa membawa barang penting, tapi tidak penting-penting amat.",
        "Kamu akan tertawa saat menyadari betapa seriusnya kamu dalam hal yang sepele.",
        "Hari ini kamu akan menemukan aplikasi baru yang tidak pernah kamu gunakan lagi setelah diunduh.",
        "Orang yang duduk disampingmu adalah jodohmu",
        "Orang yang duduk disampingmu adalah jodohmu",
        "Besok kamu akan menemukan kucing yang bisa bicara.",
        "Kamu akan bertemu alien di warung kopi.",
        "Seseorang akan memberimu donat gratis hari ini.",
        "Jangan lupa membawa sandal saat berlari maraton besok!",
        "Ada kemungkinan besar kamu akan menemukan harta karun di halaman belakang."
];

// Mengambil ramalan acak secara langsung
document.getElementById("ramalan").innerHTML = ramalan[Math.floor(Math.random() * ramalan.length)];


